/*
* Filename: symptomController.js
* Author: LUIS RAMIREZ
* Description: symtomController.js holds all the controller actions for symptoms
* Date: March 30, 2018
*/

const db = require('../models/db');

const symptomController = {};

/**
 * Function Name: createSymptom
 * Function Prototype: function symptoms(req, res);
 * Description: addes an new instance of symptom with
 * Parameters:
 *   @param req - http.IncomingRequest - req.body.user_id, req.body.type, req.body.notes
 * { user_id: INT, type: VARCHAR, notes: VARCHAR }
 *   @param res - http.ServerResponse
 * Side Effects: None
 * Error Conditions:
 *   If the database fails to insert new user, error is thrown
 * Return Value:
 *   @return Response of success
 */


//Creates new symptom for specific user
symptomController.createSymptom = (req, res, next) => {
    console.log(req.body);
    const { type } = req.body;
    const addSympTxt = (`INSERT INTO symptom (type)
                        VALUES ('acne');`);
    console.log(addSympTxt);
    db.query(addSympTxt, (err,rows) => {
        if (err) {
            throw new Error('DB QUERY FAILED TO ADD NEW SYMPTOM', err);
        }
        res.send(`ok`);
    });
};

/**
 * Function Name: readSymptom
 * Function Prototype: function symptoms(req, res);
 * Description: read all data associated with symptom type
 * Parameters:
 *   @param req - http.IncomingRequest - req.body.type,
 * searched for {  "type": "migraine" }
 * finds { "userId": "30", "type": "migraine", "notes": "migraines hurt" }

 *   @param res - http.ServerResponse
 * Side Effects: None
 * Error Conditions:
 *   If the database fails to find return error
 * Return Value:
 *   @return Response of success
 */
symptomController.readSymptom = (req, res, next) => {
    const {  type } = req.body;
    // const readSympTxt = (`SELECT * FROM symptoms WHERE type='${type}';`);
    const readSympTxt = (`SELECT * FROM symptom, entry WHERE symptom_id = entry_id`); //specify with join table what to select
    db.query(readSympTxt, (err, result) => {
        if (err) {
            throw new Error('DB QUERY FAILED TO ADD NEW SYMPTOM TO DATABASE', err);
        }
//  **
//  * Function Name: wrapper ===> function data()  and funciton formatTable()
//  * Function Prototype: taked an array of objects dataWrapper([{},{},{},{}]) takes a single obj formatTable({})
//  * Description: format table obtained from query into an array of nested objects
//  * Error Conditions: return empty array
//  * Return Value:
// [ {  \"03\":{
//         \"31\":{
//            \"symptom\":{
//               \"type\":\"migrasdsine\",
//               \"notes\":\"misdfsg\",
//               \"createdAt\":\"03-31-\\\"2018\"
//            }
//         }
//      }
//   }, {
//      \"03\":{
//         \"31\":{
//            \"symptom\":{
//               \"type\":\"migrasdsine\",
//               \"notes\":\"misdfsg\",
//               \"createdAt\":\"03-31-\\\"2018\"
//            }
//         }
//      }
//   }
//  */
        let data = (tableObj)=> {
          console.log("symptomController ln95", tableObj)
            return tableObj.map(obj => {
              console.log('symptomController ln97', obj)
                return formatTable(obj);
            })
        };
        let formatTable = (obj) => {
            let calendarObj = {};
              //        V Here can we replace with 'entry_date'?
            // let month = JSON.stringify(obj.created_at).split('-')[1];
            // let day = JSON.stringify(obj.created_at).split('-')[2].slice(0,2);

            let symptomType = obj.type;
            let symptomNote = obj.notes;
                        //        V Here can we replace with 'entry_date'?
            let symptomCreatedAt = JSON.stringify(obj.created_at).split('-')[1] +
                                   '-' + JSON.stringify(obj.created_at).split('-')[2].slice(0,2) +
                                   '-' + JSON.stringify(obj.created_at).split('-')[0];
            calendarObj[month] = {};
            calendarObj[month][day] = {}
            calendarObj[month][day].symptom = {
                "symptom_id":symptomType,
                "notes": symptomNote,
                "entry_date": entry_date
            }
            return createCalendarObj(calendarObj);
        }
        let createCalendarObj = (arrOfObj) => {
            let newArr = [arrOfObj];
            let calendar = {
    "January":{
        1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }

    },
    "February":{
        1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }
    },
    "March":{
        1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }
    },
    "April":{
        1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }
    },
    "May":{
        1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }
    },
    "June":{
        1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }
    },
    "July":{
        1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }
    },
    "August":{
         1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }
    },
    "September":{
         1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }
    },
    "October":{
         1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }
    },
    "November":{
        1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }
    },
    "December":{ 1: {
            type:[],
            notes:[],
            createdAt:[]
        },
        2:{
            type:[],
            notes:[],
            createdAt:[]
        },
        3:{
            type:[],
            notes:[],
            createdAt:[]
        },
        4:{
            type:[],
            notes:[],
            createdAt:[]
        },
        5:{
            type:[],
            notes:[],
            createdAt:[]
        },
        6:{
            type:[],
            notes:[],
            createdAt:[]
        },
        7:{
            type:[],
            notes:[],
            createdAt:[]
        },
        8:{
            type:[],
            notes:[],
            createdAt:[]
        },
        9:{
            type:[],
            notes:[],
            createdAt:[]
        },
        10:{
            type:[],
            notes:[],
            createdAt:[]
        },
        11:{
            type:[],
            notes:[],
            createdAt:[]
        },
        12:{
            type:[],
            notes:[],
            createdAt:[]
        },
        13:{
            type:[],
            notes:[],
            createdAt:[]
        },
        14:{
            type:[],
            notes:[],
            createdAt:[]
        },
        15:{
            type:[],
            notes:[],
            createdAt:[]
        },
        16:{
            type:[],
            notes:[],
            createdAt:[]
        },
        17:{
            type:[],
            notes:[],
            createdAt:[]
        },
        18:{
            type:[],
            notes:[],
            createdAt:[]
        },
        19:{
            type:[],
            notes:[],
            createdAt:[]
        },
        20:{
            type:[],
            notes:[],
            createdAt:[]
        },
        21:{
            type:[],
            notes:[],
            createdAt:[]
        },
        22:{
            type:[],
            notes:[],
            createdAt:[]
        },
        23:{
            type:[],
            notes:[],
            createdAt:[]
        },
        24:{
            type:[],
            notes:[],
            createdAt:[]
        },
        25:{
            type:[],
            notes:[],
            createdAt:[]
        },
        26:{
            type:[],
            notes:[],
            createdAt:[]
        },
        27:{
            type:[],
            notes:[],
            createdAt:[]
        },
        28:{
            type:[],
            notes:[],
            createdAt:[]
        },
        29:{
            type:[],
            notes:[],
            createdAt:[]
        },
        30:{
            type:[],
            notes:[],
            createdAt:[]
        },
        31:{
            type:[],
            notes:[],
            createdAt:[]
        }
    }
}
          //checks date for cal, pushes db info for date if true
           newArr.filter(obj => {
                for (let key in obj ){
                    if (key === '01'){
                        for ( let newKey in obj[key]){
                            if ( newKey === '01' ){
                                calendar.January['1'].type.push(obj[key]['01'].symptom.type);
                                calendar.January['1'].notes.push(obj[key]['01'].symptom.notes);
                             }
                        }
                    }
                    if (key === '02'){
                        for ( let newKey in obj[key]){
                            if ( newKey === '01' ){
                                calendar.February['1'].type.push(obj[key]['01'].symptom.type);
                                calendar.February['1'].notes.push(obj[key]['01'].type.notes);
                             }
                        }
                    }

                    if (key === '03'){
                        for ( let newKey in obj[key]){
                            if ( newKey === '31' ){
                                calendar.March['31'].type.push(obj[key]['31'].symptom.type);
                                calendar.MArch['31'].notes.push(obj[key]['31'].symptom.notes);
                             }
                             if ( newKey === '01' ){
                                calendar.March['1'].type.push(obj[key]['01'].symptom.type);
                                calendar.MArch['1'].notes.push(obj[key]['01'].symptom.notes);
                             }
                             if ( newKey === '02' ){
                                calendar.March['2'].type.push(obj[key]['02'].symptom.type);
                                calendar.MArch['2'].notes.push(obj[key]['02'].symptom.notes);
                             }
                             if ( newKey === '03' ){
                                calendar.March['3'].type.push(obj[key]['03'].symptom.type);
                                calendar.MArch['3'].notes.push(obj[key]['03'].symptom.notes);
                             }
                             if ( newKey === '04' ){
                                calendar.March['4'].type.push(obj[key]['04'].symptom.type);
                                calendar.MArch['4'].notes.push(obj[key]['04'].symptom.notes);
                             }
                             if ( newKey === '05' ){
                                calendar.March['5'].type.push(obj[key]['05'].symptom.type);
                                calendar.MArch['5'].notes.push(obj[key]['05'].symptom.notes);
                             }
                             if ( newKey === '06' ){
                                calendar.March['6'].type.push(obj[key]['06'].symptom.type);
                                calendar.MArch['6'].notes.push(obj[key]['06'].symptom.notes);
                             }
                             if ( newKey === '07' ){
                                calendar.March['7'].type.push(obj[key]['07'].symptom.type);
                                calendar.MArch['7'].notes.push(obj[key]['07'].symptom.notes);
                             }
                             if ( newKey === '08' ){
                                calendar.March['8'].type.push(obj[key]['08'].symptom.type);
                                calendar.MArch['8'].notes.push(obj[key]['08'].symptom.notes);
                             }
                             if ( newKey === '09' ){
                                calendar.March['9'].type.push(obj[key]['09'].symptom.type);
                                calendar.MArch['9'].notes.push(obj[key]['09'].symptom.notes);
                             }
                             if ( newKey === '10' ){
                                calendar.March['10'].type.push(obj[key]['10'].symptom.type);
                                calendar.MArch['10'].notes.push(obj[key]['10'].symptom.notes);
                             }
                             if ( newKey === '11' ){
                                calendar.March['11'].type.push(obj[key]['11'].symptom.type);
                                calendar.MArch['11'].notes.push(obj[key]['11'].symptom.notes);
                             }
                             if ( newKey === '12' ){
                                calendar.March['12'].type.push(obj[key]['12'].symptom.type);
                                calendar.MArch['12'].notes.push(obj[key]['12'].symptom.notes);
                             }
                             if ( newKey === '13' ){
                                calendar.March['13'].type.push(obj[key]['13'].symptom.type);
                                calendar.MArch['13'].notes.push(obj[key]['13'].symptom.notes);
                             }
                             if ( newKey === '14' ){
                                calendar.March['14'].type.push(obj[key]['14'].symptom.type);
                                calendar.MArch['14'].notes.push(obj[key]['14'].symptom.notes);
                             }
                             if ( newKey === '15' ){
                                calendar.March['15'].type.push(obj[key]['15'].symptom.type);
                                calendar.MArch['15'].notes.push(obj[key]['15'].symptom.notes);
                             }
                             if ( newKey === '16' ){
                                calendar.March['16'].type.push(obj[key]['16'].symptom.type);
                                calendar.MArch['16'].notes.push(obj[key]['16'].symptom.notes);
                             }
                             if ( newKey === '17' ){
                                calendar.March['17'].type.push(obj[key]['17'].symptom.type);
                                calendar.MArch['17'].notes.push(obj[key]['17'].symptom.notes);
                             }
                             if ( newKey === '18' ){
                                calendar.March['18'].type.push(obj[key]['18'].symptom.type);
                                calendar.MArch['18'].notes.push(obj[key]['18'].symptom.notes);
                             }
                             if ( newKey === '19' ){
                                calendar.March['19'].type.push(obj[key]['19'].symptom.type);
                                calendar.MArch['19'].notes.push(obj[key]['19'].symptom.notes);
                             }
                             if ( newKey === '20' ){
                                calendar.March['20'].type.push(obj[key]['20'].symptom.type);
                                calendar.MArch['20'].notes.push(obj[key]['20'].symptom.notes);
                             }
                             if ( newKey === '21' ){
                                calendar.March['21'].type.push(obj[key]['21'].symptom.type);
                                calendar.MArch['21'].notes.push(obj[key]['21'].symptom.notes);
                             }
                             if ( newKey === '22' ){
                                calendar.March['22'].type.push(obj[key]['22'].symptom.type);
                                calendar.MArch['22'].notes.push(obj[key]['22'].symptom.notes);
                             }
                             if ( newKey === '23' ){
                                calendar.March['23'].type.push(obj[key]['23'].symptom.type);
                                calendar.MArch['23'].notes.push(obj[key]['23'].symptom.notes);
                             }
                             if ( newKey === '24' ){
                                calendar.March['24'].type.push(obj[key]['24'].symptom.type);
                                calendar.MArch['24'].notes.push(obj[key]['24'].symptom.notes);
                             }
                             if ( newKey === '25' ){
                                calendar.March['25'].type.push(obj[key]['25'].symptom.type);
                                calendar.MArch['25'].notes.push(obj[key]['25'].symptom.notes);
                             }
                             if ( newKey === '26' ){
                                calendar.March['26'].type.push(obj[key]['26'].symptom.type);
                                calendar.MArch['26'].notes.push(obj[key]['26'].symptom.notes);
                             }
                             if ( newKey === '28' ){
                                calendar.March['28'].type.push(obj[key]['28'].symptom.type);
                                calendar.MArch['28'].notes.push(obj[key]['28'].symptom.notes);
                             }
                             if ( newKey === '29' ){
                                calendar.March['29'].type.push(obj[key]['29'].symptom.type);
                                calendar.MArch['29'].notes.push(obj[key]['29'].symptom.notes);
                             }
                             if ( newKey === '30' ){
                                calendar.March['30'].type.push(obj[key]['30'].symptom.type);
                                calendar.MArch['30'].notes.push(obj[key]['30'].symptom.notes);
                             }
                        }
                    }

                    if (key === '04'){
                        for ( let newKey in obj[key]){
                            if ( newKey === '01' ){
                                calendar.April['1'].type.push(obj[key]['01'].symptom.type);
                                calendar.April['1'].notes.push(obj[key]['01'].symptom.notes);
                             }
                        }
                    }
                }

            });

        return calendar;

        }

        console.log(data(result.rows))
        res.send(data(result.rows));
    });


/**
 * Function Name: updateSymptom
 * Description: updateSymptoms by changing symptom type value and new notes for all table (query needs to be refomated to only change on type)
 * Parameters:
 *   @param req - http.IncomingRequest  req.body.type, req.body.notes
 *   { type: VARCHAR, notes:VARCHAR }
 *   @param res - http.ServerResponse
 * * Error Conditions:
 *   If the database fails to find return error
 * Return Value:
 *   @return None
 */
//        check funtionality
symptomController.updateSymptom = (req, res, next) => {
    const { type } = req.body;
    const updateSympTxt = (`UPDATE symptoms SET type='${type}'`);
    //unable to read below - to add results to query to update/remove
    db.query(updateSympTxt, (err) => {
        if (err) {
            throw new Error('DB QUERY FAILED TO UPDATE NEW SYMPTOM TO DATABASE', err);
        }
        res.send('ok');
    });
}

/**
 * Function Name: deletesymptom
 * Description: delteSymptom by selecting type and notes
 * Parameters:
 *   @param req - http.IncomingRequest  req.body.type, req.body.notes
 *   {  "type": "migraine", "notes": "migraines hurt" }
 *   @param res - http.ServerResponse
 *  * Error Conditions:
 *   If the database fails to find return error
 * Return Value:
 *   @return None
 */

//        Check functionality
symptomController.deleteSymptom = (req, res, next) => {
    const { type } = req.body;
    const deleteSympTxt = (`DELETE FROM "symptoms" WHERE type='${type}' AND notes='${notes}'`);
    db.query(deleteSympTxt, (err) => {
        if (err) {
            throw new Error('DB QUERY FAILED TO DELETE FROM DATABASE', err);
        }
        res.send('ok');
    });
  }
}

module.exports = symptomController;
